// DevSecOps Dashboard - Mock Data
// Design: Clean Governance Dashboard | IBM Plex Sans + IBM Plex Mono

import type {
  Vulnerability,
  CrossAnalysisItem,
  IsmpItem,
  ScanSummary,
  ToolChartData,
  CategoryChartData,
  Deployment,
} from './types';

export const mockScanSummary: ScanSummary = {
  lastScanTime: '2026-03-17T08:42:00+09:00',
  totalVulnerabilities: 87,
  highCount: 14,
  mediumCount: 38,
  lowCount: 35,
  infoCount: 0,
  crossVerifiedHighCount: 9,
  ismsPCompliance: 73.5,
  pipelineStatus: 'success',
  pipelineStage: 'SAST 완료',
  pipelineProgress: 100,
};

export const mockDeployments: Deployment[] = [
  {
    id: 'deploy-001',
    name: 'Production Release v2.4.1',
    version: '2.4.1',
    environment: 'prod',
    status: 'success',
    deployedAt: '2026-03-17T08:42:00+09:00',
    scanSummary: mockScanSummary,
    vulnerabilityCount: 87,
    ismsPCompliance: 73.5,
    pipelineProgress: 100,
  },
  {
    id: 'deploy-002',
    name: 'Staging Release v2.4.0',
    version: '2.4.0',
    environment: 'staging',
    status: 'success',
    deployedAt: '2026-03-16T15:30:00+09:00',
    scanSummary: {
      lastScanTime: '2026-03-16T15:30:00+09:00',
      totalVulnerabilities: 52,
      highCount: 8,
      mediumCount: 28,
      lowCount: 16,
      infoCount: 0,
      crossVerifiedHighCount: 5,
      ismsPCompliance: 81.2,
      pipelineStatus: 'success',
      pipelineStage: 'DAST 완료',
      pipelineProgress: 100,
    },
    vulnerabilityCount: 52,
    ismsPCompliance: 81.2,
    pipelineProgress: 100,
  },
  {
    id: 'deploy-003',
    name: 'Development Build v2.3.9',
    version: '2.3.9',
    environment: 'dev',
    status: 'success',
    deployedAt: '2026-03-15T10:15:00+09:00',
    scanSummary: {
      lastScanTime: '2026-03-15T10:15:00+09:00',
      totalVulnerabilities: 124,
      highCount: 22,
      mediumCount: 65,
      lowCount: 37,
      infoCount: 0,
      crossVerifiedHighCount: 14,
      ismsPCompliance: 62.3,
      pipelineStatus: 'success',
      pipelineStage: '이미지 스캔 완료',
      pipelineProgress: 80,
    },
    vulnerabilityCount: 124,
    ismsPCompliance: 62.3,
    pipelineProgress: 80,
  },
  {
    id: 'deploy-004',
    name: 'Hotfix Release v2.3.8-patch1',
    version: '2.3.8-patch1',
    environment: 'prod',
    status: 'success',
    deployedAt: '2026-03-14T14:45:00+09:00',
    scanSummary: {
      lastScanTime: '2026-03-14T14:45:00+09:00',
      totalVulnerabilities: 45,
      highCount: 6,
      mediumCount: 22,
      lowCount: 17,
      infoCount: 0,
      crossVerifiedHighCount: 3,
      ismsPCompliance: 85.6,
      pipelineStatus: 'success',
      pipelineStage: '배포 완료',
      pipelineProgress: 100,
    },
    vulnerabilityCount: 45,
    ismsPCompliance: 85.6,
    pipelineProgress: 100,
  },
  {
    id: 'deploy-005',
    name: 'Feature Branch v2.5.0-beta',
    version: '2.5.0-beta',
    environment: 'staging',
    status: 'failed',
    deployedAt: '2026-03-13T09:20:00+09:00',
    scanSummary: {
      lastScanTime: '2026-03-13T09:20:00+09:00',
      totalVulnerabilities: 156,
      highCount: 28,
      mediumCount: 89,
      lowCount: 39,
      infoCount: 0,
      crossVerifiedHighCount: 19,
      ismsPCompliance: 54.8,
      pipelineStatus: 'failed',
      pipelineStage: 'SAST 실패',
      pipelineProgress: 45,
    },
    vulnerabilityCount: 156,
    ismsPCompliance: 54.8,
    pipelineProgress: 45,
  },
];

export const mockVulnerabilities: Vulnerability[] = [
  {
    id: 'V-001',
    severity: 'HIGH',
    category: 'SQL Injection',
    tool: 'Semgrep',
    file: 'src/api/userController.ts',
    line: 142,
    cwe: 'CWE-89',
    description: '사용자 입력값이 SQL 쿼리에 직접 삽입되어 SQL Injection 취약점이 존재합니다.',
    confidence: 'HIGH',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-002',
    severity: 'HIGH',
    category: 'Command Injection',
    tool: 'Bandit',
    file: 'scripts/deploy.py',
    line: 67,
    cwe: 'CWE-78',
    description: 'os.system() 호출에 외부 입력이 포함되어 명령어 주입 취약점이 발생할 수 있습니다.',
    confidence: 'HIGH',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-003',
    severity: 'HIGH',
    category: 'Hardcoded Secret',
    tool: 'Gitleaks',
    file: 'config/database.yml',
    line: 23,
    cwe: 'CWE-798',
    description: 'AWS 액세스 키가 소스코드에 하드코딩되어 있습니다.',
    confidence: 'HIGH',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-004',
    severity: 'HIGH',
    category: 'Path Traversal',
    tool: 'Semgrep',
    file: 'src/utils/fileHandler.ts',
    line: 89,
    cwe: 'CWE-22',
    description: '파일 경로 검증 없이 사용자 입력이 파일 시스템 접근에 사용됩니다.',
    confidence: 'HIGH',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-005',
    severity: 'HIGH',
    category: 'XSS',
    tool: 'ESLint Security',
    file: 'src/components/UserProfile.tsx',
    line: 55,
    cwe: 'CWE-79',
    description: 'dangerouslySetInnerHTML에 사용자 입력이 직접 사용되어 XSS 취약점이 존재합니다.',
    confidence: 'HIGH',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-006',
    severity: 'HIGH',
    category: 'Insecure Deserialization',
    tool: 'Bandit',
    file: 'src/services/cacheService.py',
    line: 34,
    cwe: 'CWE-502',
    description: 'pickle.loads()를 신뢰할 수 없는 데이터에 사용하고 있습니다.',
    confidence: 'MEDIUM',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-007',
    severity: 'HIGH',
    category: 'SSRF',
    tool: 'Semgrep',
    file: 'src/api/webhookController.ts',
    line: 112,
    cwe: 'CWE-918',
    description: '사용자가 제공한 URL로 서버 측 요청이 발생하여 SSRF 취약점이 존재합니다.',
    confidence: 'HIGH',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-008',
    severity: 'HIGH',
    category: 'Broken Authentication',
    tool: 'ESLint Security',
    file: 'src/middleware/auth.ts',
    line: 28,
    cwe: 'CWE-287',
    description: 'JWT 서명 검증이 누락되어 인증 우회가 가능합니다.',
    confidence: 'HIGH',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-009',
    severity: 'HIGH',
    category: 'Cryptographic Failure',
    tool: 'Bandit',
    file: 'src/utils/crypto.py',
    line: 19,
    cwe: 'CWE-327',
    description: 'MD5 해시 알고리즘이 비밀번호 저장에 사용되고 있습니다.',
    confidence: 'HIGH',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-010',
    severity: 'HIGH',
    category: 'XXE',
    tool: 'Semgrep',
    file: 'src/parsers/xmlParser.ts',
    line: 45,
    cwe: 'CWE-611',
    description: 'XML 파서에 외부 엔티티 처리가 활성화되어 XXE 취약점이 존재합니다.',
    confidence: 'MEDIUM',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-011',
    severity: 'HIGH',
    category: 'Open Redirect',
    tool: 'ESLint Security',
    file: 'src/api/authController.ts',
    line: 78,
    cwe: 'CWE-601',
    description: '리다이렉트 URL 검증이 없어 오픈 리다이렉트 공격이 가능합니다.',
    confidence: 'HIGH',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-012',
    severity: 'HIGH',
    category: 'Hardcoded Secret',
    tool: 'Gitleaks',
    file: '.env.example',
    line: 8,
    cwe: 'CWE-798',
    description: 'GitHub Personal Access Token이 예제 파일에 실제 값으로 포함되어 있습니다.',
    confidence: 'HIGH',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-013',
    severity: 'HIGH',
    category: 'LDAP Injection',
    tool: 'Semgrep',
    file: 'src/services/ldapService.ts',
    line: 93,
    cwe: 'CWE-90',
    description: 'LDAP 쿼리에 사용자 입력이 이스케이프 없이 삽입됩니다.',
    confidence: 'MEDIUM',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-014',
    severity: 'HIGH',
    category: 'Insecure Direct Object Reference',
    tool: 'Bandit',
    file: 'src/api/documentController.py',
    line: 156,
    cwe: 'CWE-639',
    description: '접근 제어 없이 문서 ID로 직접 접근이 가능합니다.',
    confidence: 'HIGH',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-015',
    severity: 'MEDIUM',
    category: 'Missing Security Headers',
    tool: 'ESLint Security',
    file: 'src/server/middleware.ts',
    line: 12,
    cwe: 'CWE-693',
    description: 'Content-Security-Policy 헤더가 설정되지 않았습니다.',
    confidence: 'HIGH',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-016',
    severity: 'MEDIUM',
    category: 'Insecure Cookie',
    tool: 'Semgrep',
    file: 'src/middleware/session.ts',
    line: 34,
    cwe: 'CWE-614',
    description: '세션 쿠키에 Secure 플래그가 설정되지 않았습니다.',
    confidence: 'HIGH',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-017',
    severity: 'MEDIUM',
    category: 'Weak Password Policy',
    tool: 'Bandit',
    file: 'src/validators/passwordValidator.py',
    line: 22,
    cwe: 'CWE-521',
    description: '비밀번호 최소 길이가 6자로 너무 짧게 설정되어 있습니다.',
    confidence: 'MEDIUM',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-018',
    severity: 'MEDIUM',
    category: 'Information Exposure',
    tool: 'Semgrep',
    file: 'src/api/errorHandler.ts',
    line: 45,
    cwe: 'CWE-209',
    description: '에러 응답에 스택 트레이스가 포함되어 내부 구조가 노출됩니다.',
    confidence: 'HIGH',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-019',
    severity: 'MEDIUM',
    category: 'CSRF',
    tool: 'ESLint Security',
    file: 'src/api/formController.ts',
    line: 67,
    cwe: 'CWE-352',
    description: 'POST 요청에 CSRF 토큰 검증이 누락되었습니다.',
    confidence: 'MEDIUM',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-020',
    severity: 'MEDIUM',
    category: 'Dependency Vulnerability',
    tool: 'Trivy',
    file: 'package.json',
    line: 1,
    cwe: 'CWE-1035',
    description: 'lodash 4.17.20 버전에 프로토타입 오염 취약점이 존재합니다.',
    confidence: 'HIGH',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-021',
    severity: 'MEDIUM',
    category: 'Dependency Vulnerability',
    tool: 'Trivy',
    file: 'requirements.txt',
    line: 15,
    cwe: 'CWE-1035',
    description: 'Django 3.2.1 버전에 SQL Injection 취약점이 존재합니다.',
    confidence: 'HIGH',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-022',
    severity: 'MEDIUM',
    category: 'Insecure Randomness',
    tool: 'Bandit',
    file: 'src/utils/tokenGenerator.py',
    line: 11,
    cwe: 'CWE-330',
    description: 'random 모듈이 보안 토큰 생성에 사용되고 있습니다. secrets 모듈을 사용해야 합니다.',
    confidence: 'HIGH',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-023',
    severity: 'MEDIUM',
    category: 'Logging Sensitive Data',
    tool: 'Semgrep',
    file: 'src/services/paymentService.ts',
    line: 88,
    cwe: 'CWE-532',
    description: '신용카드 번호가 로그에 기록되고 있습니다.',
    confidence: 'HIGH',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-024',
    severity: 'MEDIUM',
    category: 'Race Condition',
    tool: 'Semgrep',
    file: 'src/services/inventoryService.ts',
    line: 134,
    cwe: 'CWE-362',
    description: '재고 감소 로직에 동시성 제어가 없어 레이스 컨디션이 발생할 수 있습니다.',
    confidence: 'MEDIUM',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-025',
    severity: 'LOW',
    category: 'Missing Input Validation',
    tool: 'ESLint Security',
    file: 'src/components/SearchBar.tsx',
    line: 23,
    cwe: 'CWE-20',
    description: '검색 입력에 길이 제한이 없습니다.',
    confidence: 'LOW',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-026',
    severity: 'LOW',
    category: 'Verbose Error Message',
    tool: 'Bandit',
    file: 'src/api/loginController.py',
    line: 56,
    cwe: 'CWE-209',
    description: '로그인 실패 시 사용자 존재 여부를 알 수 있는 메시지가 반환됩니다.',
    confidence: 'MEDIUM',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-027',
    severity: 'LOW',
    category: 'Outdated TLS',
    tool: 'Trivy',
    file: 'nginx.conf',
    line: 34,
    cwe: 'CWE-326',
    description: 'TLS 1.0/1.1이 활성화되어 있습니다. TLS 1.2 이상만 허용해야 합니다.',
    confidence: 'HIGH',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-028',
    severity: 'LOW',
    category: 'Debug Mode Enabled',
    tool: 'Semgrep',
    file: 'config/app.config.ts',
    line: 7,
    cwe: 'CWE-489',
    description: '프로덕션 환경에서 디버그 모드가 활성화되어 있습니다.',
    confidence: 'MEDIUM',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-029',
    severity: 'HIGH',
    category: 'IaC Misconfiguration',
    tool: 'tfsec',
    file: 'infrastructure/main.tf',
    line: 12,
    cwe: 'CWE-940',
    description: 'AWS S3 버킷이 공개적으로 설정되어 있습니다.',
    confidence: 'HIGH',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-030',
    severity: 'HIGH',
    category: 'IaC Secret',
    tool: 'Checkov',
    file: 'infrastructure/main.tf',
    line: 25,
    cwe: 'CWE-798',
    description: '인프라 코드에 AWS 자격 증명이 하드코딩되어 있습니다.',
    confidence: 'HIGH',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-031',
    severity: 'MEDIUM',
    category: 'Code Quality',
    tool: 'SonarQube',
    file: 'src/utils/helpers.ts',
    line: 53,
    cwe: 'CWE-398',
    description: '복잡도 높은 함수가 발견되어 유지보수가 어려울 수 있습니다.',
    confidence: 'MEDIUM',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-032',
    severity: 'LOW',
    category: 'Dependency Vulnerability',
    tool: 'Dep-Check',
    file: 'package.json',
    line: 0,
    cwe: 'CWE-829',
    description: '사용되지 않는 의존성이 포함되어 있습니다.',
    confidence: 'LOW',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-033',
    severity: 'HIGH',
    category: 'Image Vulnerability',
    tool: 'Trivy',
    file: 'Dockerfile',
    line: 1,
    cwe: 'CWE-829',
    description: '기본 이미지에 알려진 취약점이 포함되어 있습니다.',
    confidence: 'HIGH',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-034',
    severity: 'HIGH',
    category: 'Web Scanner Finding',
    tool: 'OWASP ZAP',
    file: 'http://localhost:3000/login',
    line: 0,
    cwe: 'CWE-79',
    description: 'XSS 취약점이 로그인 폼에서 탐지되었습니다.',
    confidence: 'HIGH',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'V-035',
    severity: 'MEDIUM',
    category: 'SIEM Alert',
    tool: 'SIEM',
    file: 'SIEM Event',
    line: 0,
    cwe: 'CWE-200',
    description: '비정상적인 로그인 시도가 탐지되었습니다.',
    confidence: 'MEDIUM',
    detectedAt: '2026-03-17T08:42:00+09:00',
  },
];

export const mockCrossAnalysis: CrossAnalysisItem[] = [
  {
    id: 'CA-001',
    severity: 'HIGH',
    category: 'SQL Injection',
    tools: ['Semgrep', 'Bandit', 'ESLint Security'],
    file: 'src/api/userController.ts',
    line: 142,
    cwe: 'CWE-89',
    description: '3개 도구에서 동시 탐지된 SQL Injection 취약점. 즉시 수정이 필요합니다.',
    confidence: 'HIGH',
    detectionCount: 3,
    llmJudgment: {
      id: 'LLM-001',
      vulnerabilityId: 'CA-001',
      judgment: 'TRUE_POSITIVE',
      confidence: 95,
      reasoning: '사용자 입력이 SQL 쿼리에 직접 연결되는 패턴으로, 실제 SQL Injection 취약점이 존재합니다. prepared statement로 수정이 필요합니다.',
      recommendedAction: 'Prepared Statement 또는 ORM 사용으로 전환',
      riskAssessment: 'CRITICAL',
      judgedAt: '2026-03-17T08:45:00+09:00',
    },
  },
  {
    id: 'CA-002',
    severity: 'HIGH',
    category: 'Hardcoded Secret',
    tools: ['Gitleaks', 'Semgrep'],
    file: 'config/database.yml',
    line: 23,
    cwe: 'CWE-798',
    description: '2개 도구에서 동시 탐지된 하드코딩된 시크릿. 즉시 교체가 필요합니다.',
    confidence: 'HIGH',
    detectionCount: 2,
    llmJudgment: {
      id: 'LLM-002',
      vulnerabilityId: 'CA-002',
      judgment: 'TRUE_POSITIVE',
      confidence: 98,
      reasoning: '실제 데이터베이스 연결 정보가 하드코딩되어 있어 보안 위험이 높습니다. 환경 변수 또는 시크릿 관리 시스템으로 즉시 이동해야 합니다.',
      recommendedAction: 'AWS Secrets Manager 또는 HashiCorp Vault로 마이그레이션',
      riskAssessment: 'CRITICAL',
      judgedAt: '2026-03-17T08:45:00+09:00',
    },
  },
  {
    id: 'CA-003',
    severity: 'HIGH',
    category: 'XSS',
    tools: ['Semgrep', 'ESLint Security'],
    file: 'src/components/UserProfile.tsx',
    line: 55,
    cwe: 'CWE-79',
    description: '2개 도구에서 동시 탐지된 XSS 취약점.',
    confidence: 'HIGH',
    detectionCount: 2,
    llmJudgment: {
      id: 'LLM-003',
      vulnerabilityId: 'CA-003',
      judgment: 'TRUE_POSITIVE',
      confidence: 92,
      reasoning: '사용자 입력이 innerHTML에 직접 삽입되는 패턴으로 XSS 공격이 가능합니다. 입력 검증 및 sanitization이 필요합니다.',
      recommendedAction: 'DOMPurify 라이브러리 사용 또는 React의 dangerouslySetInnerHTML 대신 안전한 렌더링 방식 사용',
      riskAssessment: 'HIGH',
      judgedAt: '2026-03-17T08:45:00+09:00',
    },
  },
  {
    id: 'CA-004',
    severity: 'HIGH',
    category: 'Broken Authentication',
    tools: ['Semgrep', 'ESLint Security', 'Bandit'],
    file: 'src/middleware/auth.ts',
    line: 28,
    cwe: 'CWE-287',
    description: '3개 도구에서 동시 탐지된 인증 취약점. 즉시 수정이 필요합니다.',
    confidence: 'HIGH',
    detectionCount: 3,
    llmJudgment: {
      id: 'LLM-004',
      vulnerabilityId: 'CA-004',
      judgment: 'TRUE_POSITIVE',
      confidence: 96,
      reasoning: 'JWT 토큰 검증 로직이 불완전하여 인증 우회가 가능합니다. 서명 검증 및 만료 시간 검증이 모두 필요합니다.',
      recommendedAction: 'jsonwebtoken 라이브러리의 verify() 메소드 사용 및 적절한 에러 처리 추가',
      riskAssessment: 'CRITICAL',
      judgedAt: '2026-03-17T08:45:00+09:00',
    },
  },
  {
    id: 'CA-005',
    severity: 'HIGH',
    category: 'Cryptographic Failure',
    tools: ['Bandit', 'Semgrep'],
    file: 'src/utils/crypto.py',
    line: 19,
    cwe: 'CWE-327',
    description: '2개 도구에서 동시 탐지된 암호화 취약점.',
    confidence: 'HIGH',
    detectionCount: 2,
    llmJudgment: {
      id: 'LLM-005',
      vulnerabilityId: 'CA-005',
      judgment: 'TRUE_POSITIVE',
      confidence: 94,
      reasoning: 'MD5 해시가 비밀번호 저장에 사용되고 있어 무차별 대입 공격에 취약합니다. bcrypt 또는 Argon2로 변경해야 합니다.',
      recommendedAction: 'bcrypt 라이브러리로 마이그레이션 및 기존 해시 재생성',
      riskAssessment: 'HIGH',
      judgedAt: '2026-03-17T08:45:00+09:00',
    },
  },
  {
    id: 'CA-006',
    severity: 'HIGH',
    category: 'Command Injection',
    tools: ['Bandit', 'Semgrep'],
    file: 'scripts/deploy.py',
    line: 67,
    cwe: 'CWE-78',
    description: '2개 도구에서 동시 탐지된 명령어 주입 취약점.',
    confidence: 'HIGH',
    detectionCount: 2,
    llmJudgment: {
      id: 'LLM-006',
      vulnerabilityId: 'CA-006',
      judgment: 'TRUE_POSITIVE',
      confidence: 97,
      reasoning: '사용자 입력이 shell 명령어에 직접 삽입되어 명령어 주입 공격이 가능합니다. subprocess 모듈의 리스트 형태 사용으로 수정해야 합니다.',
      recommendedAction: 'subprocess.run()에 리스트 형태의 명령어 사용 및 shell=False 설정',
      riskAssessment: 'CRITICAL',
      judgedAt: '2026-03-17T08:45:00+09:00',
    },
  },
  {
    id: 'CA-007',
    severity: 'MEDIUM',
    category: 'Dependency Vulnerability',
    tools: ['Trivy', 'Semgrep'],
    file: 'package.json',
    line: 1,
    cwe: 'CWE-1035',
    description: '2개 도구에서 동시 탐지된 의존성 취약점.',
    confidence: 'HIGH',
    detectionCount: 2,
    llmJudgment: {
      id: 'LLM-007',
      vulnerabilityId: 'CA-007',
      judgment: 'TRUE_POSITIVE',
      confidence: 89,
      reasoning: 'lodash 라이브러리에 프로토타입 오염 취약점이 존재합니다. 최신 버전으로 업데이트하거나 대체 라이브러리 사용을 고려해야 합니다.',
      recommendedAction: 'lodash를 최신 버전으로 업데이트 또는 lodash-es로 변경',
      riskAssessment: 'MEDIUM',
      judgedAt: '2026-03-17T08:45:00+09:00',
    },
  },
  {
    id: 'CA-008',
    severity: 'HIGH',
    category: 'SSRF',
    tools: ['Semgrep', 'ESLint Security'],
    file: 'src/api/webhookController.ts',
    line: 112,
    cwe: 'CWE-918',
    description: '2개 도구에서 동시 탐지된 SSRF 취약점.',
    confidence: 'HIGH',
    detectionCount: 2,
    llmJudgment: {
      id: 'LLM-008',
      vulnerabilityId: 'CA-008',
      judgment: 'TRUE_POSITIVE',
      confidence: 93,
      reasoning: '사용자가 제공한 URL로 서버 측 요청이 발생하여 내부 네트워크 스캔이 가능합니다. URL 화이트리스트 또는 요청 제한이 필요합니다.',
      recommendedAction: 'URL 화이트리스트 구현 및 요청 타임아웃 설정',
      riskAssessment: 'HIGH',
      judgedAt: '2026-03-17T08:45:00+09:00',
    },
  },
  {
    id: 'CA-010',
    severity: 'HIGH',
    category: 'IaC Misconfiguration',
    tools: ['tfsec', 'Checkov'],
    file: 'infrastructure/main.tf',
    line: 12,
    cwe: 'CWE-284',
    description: '2개 도구에서 동시 탐지된 IaC 구성 오류. S3 버킷이 공개적으로 접근 가능합니다.',
    confidence: 'HIGH',
    detectionCount: 2,
    llmJudgment: {
      id: 'LLM-010',
      vulnerabilityId: 'CA-010',
      judgment: 'TRUE_POSITIVE',
      confidence: 96,
      reasoning: 'Terraform 구성에서 S3 버킷의 ACL이 public-read로 설정되어 있어 민감한 데이터 유출 위험이 있습니다. private으로 변경해야 합니다.',
      recommendedAction: 'S3 버킷 ACL을 private으로 설정하고 버킷 정책 검토',
      riskAssessment: 'CRITICAL',
      judgedAt: '2026-03-17T08:45:00+09:00',
    },
  },
  {
    id: 'CA-011',
    severity: 'HIGH',
    category: 'IaC Security Group',
    tools: ['tfsec', 'Checkov'],
    file: 'infrastructure/security.tf',
    line: 45,
    cwe: 'CWE-284',
    description: '2개 도구에서 동시 탐지된 보안 그룹 구성 오류. 모든 포트가 개방되어 있습니다.',
    confidence: 'HIGH',
    detectionCount: 2,
    llmJudgment: {
      id: 'LLM-011',
      vulnerabilityId: 'CA-011',
      judgment: 'TRUE_POSITIVE',
      confidence: 98,
      reasoning: 'EC2 보안 그룹이 0.0.0.0/0으로 모든 포트를 개방하고 있어 외부 공격에 노출되어 있습니다. 특정 IP 범위로 제한해야 합니다.',
      recommendedAction: '보안 그룹 규칙을 필요한 포트와 IP 범위로 제한',
      riskAssessment: 'CRITICAL',
      judgedAt: '2026-03-17T08:45:00+09:00',
    },
  },
  {
    id: 'CA-012',
    severity: 'HIGH',
    category: 'DAST XSS',
    tools: ['OWASP ZAP', 'Semgrep'],
    file: 'src/components/UserProfile.tsx',
    line: 55,
    cwe: 'CWE-79',
    description: '2개 도구에서 동시 탐지된 XSS 취약점. 동적 분석으로 확인되었습니다.',
    confidence: 'HIGH',
    detectionCount: 2,
    llmJudgment: {
      id: 'LLM-012',
      vulnerabilityId: 'CA-012',
      judgment: 'TRUE_POSITIVE',
      confidence: 92,
      reasoning: 'OWASP ZAP의 동적 스캔에서 XSS 페이로드가 성공적으로 실행되어 실제 취약점이 확인되었습니다. 입력 검증 및 출력 인코딩이 필요합니다.',
      recommendedAction: 'DOMPurify 라이브러리 사용 또는 React의 dangerouslySetInnerHTML 대신 안전한 렌더링 방식 사용',
      riskAssessment: 'HIGH',
      judgedAt: '2026-03-17T08:45:00+09:00',
    },
  },
  {
    id: 'CA-013',
    severity: 'HIGH',
    category: 'DAST SQL Injection',
    tools: ['OWASP ZAP'],
    file: 'src/api/userController.ts',
    line: 142,
    cwe: 'CWE-89',
    description: '동적 분석에서 탐지된 SQL Injection 취약점.',
    confidence: 'HIGH',
    detectionCount: 1,
    llmJudgment: {
      id: 'LLM-013',
      vulnerabilityId: 'CA-013',
      judgment: 'TRUE_POSITIVE',
      confidence: 94,
      reasoning: 'OWASP ZAP의 SQL 인젝션 페이로드로 데이터베이스 에러가 발생하여 실제 취약점이 확인되었습니다. prepared statement로 수정이 필요합니다.',
      recommendedAction: 'Prepared Statement 또는 ORM 사용으로 전환',
      riskAssessment: 'CRITICAL',
      judgedAt: '2026-03-17T08:45:00+09:00',
    },
  },
];

export const mockIsmpItems: IsmpItem[] = [
  {
    id: 'ISMS-001',
    controlId: '2.1.1',
    domain: '정책',
    requirement: '정보보호 정책의 수립',
    status: 'PASS',
    evidence: '정보보호 정책 문서 v2.3 (2026-01-15)',
    lastChecked: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'ISMS-002',
    controlId: '2.1.2',
    domain: '정책',
    requirement: '정보보호 정책의 검토 및 승인',
    status: 'PASS',
    evidence: 'CISO 승인 기록 (2026-01-20)',
    lastChecked: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'ISMS-003',
    controlId: '2.2.1',
    domain: '조직',
    requirement: '정보보호 조직의 구성',
    status: 'PASS',
    evidence: '조직도 및 역할 정의서',
    lastChecked: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'ISMS-004',
    controlId: '2.3.1',
    domain: '인적 보안',
    requirement: '임직원 보안 교육',
    status: 'PARTIAL',
    evidence: '교육 이수율 68% (목표: 100%)',
    lastChecked: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'ISMS-005',
    controlId: '2.4.1',
    domain: '자산 관리',
    requirement: '정보자산 식별 및 분류',
    status: 'PASS',
    evidence: '자산 목록 v1.8 (2026-02-28)',
    lastChecked: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'ISMS-006',
    controlId: '2.5.1',
    domain: '접근 통제',
    requirement: '사용자 계정 관리',
    status: 'FAIL',
    evidence: '퇴직자 계정 12건 미삭제 확인',
    lastChecked: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'ISMS-007',
    controlId: '2.5.2',
    domain: '접근 통제',
    requirement: '특권 계정 관리',
    status: 'FAIL',
    evidence: '관리자 계정 공유 사용 확인',
    lastChecked: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'ISMS-008',
    controlId: '2.6.1',
    domain: '암호화',
    requirement: '암호화 정책 수립 및 적용',
    status: 'PARTIAL',
    evidence: '일부 DB 컬럼 암호화 미적용',
    lastChecked: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'ISMS-009',
    controlId: '2.7.1',
    domain: '물리 보안',
    requirement: '물리적 접근 통제',
    status: 'PASS',
    evidence: '출입 통제 시스템 운영 중',
    lastChecked: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'ISMS-010',
    controlId: '2.8.1',
    domain: '시스템 보안',
    requirement: '보안 패치 관리',
    status: 'FAIL',
    evidence: '서버 3대 OS 패치 6개월 이상 미적용',
    lastChecked: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'ISMS-011',
    controlId: '2.8.2',
    domain: '시스템 보안',
    requirement: '악성코드 방지',
    status: 'PASS',
    evidence: '전사 EDR 솔루션 배포 완료',
    lastChecked: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'ISMS-012',
    controlId: '2.9.1',
    domain: '네트워크 보안',
    requirement: '네트워크 접근 통제',
    status: 'PASS',
    evidence: 'WAF 및 방화벽 정책 적용',
    lastChecked: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'ISMS-013',
    controlId: '2.10.1',
    domain: '로그 관리',
    requirement: '보안 로그 수집 및 보관',
    status: 'PARTIAL',
    evidence: '로그 보관 기간 90일 (기준: 180일)',
    lastChecked: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'ISMS-014',
    controlId: '2.11.1',
    domain: '사고 대응',
    requirement: '침해사고 대응 절차',
    status: 'PASS',
    evidence: '침해사고 대응 매뉴얼 v1.2',
    lastChecked: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'ISMS-015',
    controlId: '2.12.1',
    domain: '공급망 보안',
    requirement: '외부 서비스 보안 관리',
    status: 'FAIL',
    evidence: '3rd party 보안 평가 미실시',
    lastChecked: '2026-03-17T08:42:00+09:00',
  },
  {
    id: 'ISMS-016',
    controlId: '2.13.1',
    domain: '개인정보 보호',
    requirement: '개인정보 처리 방침',
    status: 'PASS',
    evidence: '개인정보 처리방침 공개 및 갱신',
    lastChecked: '2026-03-17T08:42:00+09:00',
  },
];

export const mockToolChartData: ToolChartData[] = [
  { tool: 'Semgrep', HIGH: 6, MEDIUM: 12, LOW: 8, INFO: 0 },
  { tool: 'Bandit', HIGH: 4, MEDIUM: 8, LOW: 7, INFO: 0 },
  { tool: 'Gitleaks', HIGH: 2, MEDIUM: 3, LOW: 2, INFO: 0 },
  { tool: 'ESLint Security', HIGH: 2, MEDIUM: 9, LOW: 6, INFO: 0 },
  { tool: 'Trivy', HIGH: 0, MEDIUM: 6, LOW: 12, INFO: 0 },
];

export const mockCategoryChartData: CategoryChartData[] = [
  { name: 'Injection', value: 18, color: '#ef4444' },
  { name: 'Broken Auth', value: 12, color: '#f97316' },
  { name: 'Cryptographic', value: 9, color: '#f59e0b' },
  { name: 'XSS', value: 8, color: '#eab308' },
  { name: 'Dependency', value: 14, color: '#6366f1' },
  { name: 'Misconfiguration', value: 11, color: '#8b5cf6' },
  { name: 'Access Control', value: 7, color: '#3b82f6' },
  { name: 'Other', value: 8, color: '#94a3b8' },
];

export const SEVERITY_COLORS = {
  HIGH: '#ef4444',
  MEDIUM: '#f59e0b',
  LOW: '#3b82f6',
  INFO: '#94a3b8',
} as const;

export const SEVERITY_BG_COLORS = {
  HIGH: 'bg-red-50 text-red-700 border-red-200',
  MEDIUM: 'bg-amber-50 text-amber-700 border-amber-200',
  LOW: 'bg-blue-50 text-blue-700 border-blue-200',
  INFO: 'bg-slate-50 text-slate-600 border-slate-200',
} as const;

export const PIPELINE_STAGES = [
  'SAST 분석',
  '시크릿 스캔',
  '의존성 검사',
  '컨테이너 스캔',
  '교차 분석',
  'ISMS-P 점검',
  '보고서 생성',
];

import type { SecurityMonitoringSummary, ServiceStatus, EventItem, TrendChartData } from './types';

export const mockSecurityMonitoringSummary: SecurityMonitoringSummary = {
  securityScore: 78,
  activeAlarms: 4,
  guardDutyFindings: 2,
  cloudTrailStatus: '수집 중',
  recentEventTime: '2026-03-17T15:42:00+09:00',
  monitoringStatus: 'warning',
};

export const mockServiceStatuses: ServiceStatus[] = [
  {
    service: 'CloudWatch',
    status: '정상',
    details: {
      alarmCount: 3,
      recentTrigger: '2026-03-17T15:30:00+09:00',
      monitoringEnabled: true,
    },
  },
  {
    service: 'GuardDuty',
    status: '경고',
    details: {
      findingCount: 2,
      severityDistribution: { HIGH: 1, MEDIUM: 1, LOW: 0 },
      recentFinding: '2026-03-17T15:42:00+09:00',
    },
  },
  {
    service: 'CloudTrail',
    status: '정상',
    details: {
      collectionEnabled: true,
      recentEvent: '2026-03-17T15:45:00+09:00',
      apiCallCount: 156,
    },
  },
  {
    service: 'Security Hub',
    status: '주의',
    details: {
      securityScore: 78,
      failedControls: 12,
      complianceStatus: '부분 준수',
    },
  },
];

export const mockEventItems: EventItem[] = [
  {
    time: '15:42',
    service: 'GuardDuty',
    eventType: 'UnauthorizedAccess',
    severity: 'HIGH',
    resource: 'EC2 instance i-1234567890abcdef0',
    status: 'Open',
    description: '비정상적인 API 호출 패턴 감지',
  },
  {
    time: '15:30',
    service: 'CloudWatch',
    eventType: 'CPU Alarm',
    severity: 'MEDIUM',
    resource: 'ECS service web-app',
    status: 'Resolved',
    description: 'CPU 사용률 85% 초과',
  },
  {
    time: '15:21',
    service: 'CloudTrail',
    eventType: 'IAM Policy Change',
    severity: 'MEDIUM',
    resource: 'IAM role admin-role',
    status: 'Open',
    description: 'IAM 정책 변경 이벤트',
  },
  {
    time: '15:15',
    service: 'Security Hub',
    eventType: 'Compliance Failure',
    severity: 'LOW',
    resource: 'S3 bucket logs-bucket',
    status: 'Open',
    description: '버킷 암호화 설정 미흡',
  },
  {
    time: '15:10',
    service: 'GuardDuty',
    eventType: 'Suspicious Network',
    severity: 'MEDIUM',
    resource: 'VPC vpc-12345678',
    status: 'Resolved',
    description: '수상한 네트워크 트래픽 감지',
  },
];

export const mockTrendChartData: TrendChartData[] = [
  { time: '12:00', events: 2 },
  { time: '13:00', events: 1 },
  { time: '14:00', events: 3 },
  { time: '15:00', events: 5 },
  { time: '16:00', events: 2 },
];
