name: CD Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deploy environment"
        required: true
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod
      deployment_mode:
        description: "Deployment mode"
        required: true
        default: "service"
        type: choice
        options:
          - service
          - infra_only

permissions:
  contents: read
  id-token: write

jobs:
  deploy-manual:
    uses: ./.github/workflows/secureflow-dashboard-deploy.yml
    with:
      environment: ${{ inputs.environment }}
      deployment_mode: ${{ inputs.deployment_mode }}
    secrets: inherit
